INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (11, 'горячая фича', '', null);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (12, 'горячая фича', '', null);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (13, 'горячая фича', '', null);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (14, 'горячая фича', '', null);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (1, 'вы выиграли миллион', 'http://pornhub.com/', 1);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (3, 'вы выиграли миллион', 'http://pornhub.com/', 3);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (2, 'вы выиграли миллион', 'http://pornhub.com/', 2);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (10, 'вы выиграли миллиард', 'что ты мне сделаешь я в другом городе', 3);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (9, 'вы выиграли миллион', 'http://pornhub.com/', 3);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (6, 'вы выиграли миллион', 'http://pornhub.com/', 3);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (8, 'вы выиграли миллион', 'http://pornhub.com/', 2);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (5, 'вы выиграли миллион', 'http://pornhub.com/', 2);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (7, 'вы выиграли миллион', 'http://pornhub.com/', 1);
INSERT INTO public.notifications (id_notification, name, url, id_stories) VALUES (4, 'вы выиграли миллион', 'http://pornhub.com/', 1);